---
- hosts: all
  become: true
  tasks:

    - name: install apache2, libapache2-mod-php package and update cache.
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install httpd, php and update cache for fedora.
      ansible.builtin.dnf:
        name:
          - httpd
          - php
        use_backend: dnf4
        state: latest
        update_cache: yes
      when: ansible_distribution == "Fedora"
