---
- hosts: all
  become: true
  tasks:

    - name: remove apache2 and libapache2-mod-php packages and update repository index.
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: absent
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: remove httpd and php packages and update repository index in fedora.
      ansible.builtin.dnf:
        use_backend: dnf4
        name:
          - httpd
          - php
        state: absent
        update_cache: yes
      when: ansible_distribution == "Fedora"
