- name: install apache on web servers (Ubuntu)
  tags: apache,ubuntu
  ansible.builtin.apt:
    name:
      - apache2
      - libapache2-mod-php
  when: ansible_distribution == "Ubuntu"

- name: install apache on web servers (Fedora)
  tags: apache,fedora
  ansible.builtin.dnf:
    use_backend: dnf4
    name: httpd
  when: ansible_distribution == "Fedora"


- name: ensure apache is running
  tags: apache
  ansible.builtin.service:
    name: "{{ apache_service  }}"
    state: started


- name: change email address for admin
  tags: apache,fedora
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin someone@somehoww.in
  when: ansible_distribution == "Fedora"
  notify: restart_apache
